name = "PlasticityBase"
uuid = "4061fbf7-9440-4a1d-9a5e-b99f9d96b3d3"
authors = ["Joby M. Anthony III"]
version = "0.0.0-dev"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
