name = "PlasticityBase"
uuid = "4061fbf7-9440-4a1d-9a5e-b99f9d96b3d3"
authors = ["Joby M. Anthony III"]
version = "0.0.0-dev"

# [weakdeps]
# PlasticityCalibratinator = "a89bb55e-884e-48c3-ba05-e3917bd289c9"

# [extensions]
# PlasticityCalibratinatorExt = "PlasticityCalibratinator"

[compat]
julia = "1.11"
# PlasticityCalibratinator = "0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
